### ISSUE TITLE
Tribits: make package_source creates tarballs with missing BuildStatsWrappers.cmake

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#11976]
## Bug Report

@trilinos/tribits @bartlettroscoe 

After using the `make package_source` option to generate packaged source code tarballs for a configuration of Trilinos, if I try to configure the packaged source with the same configuration I encounter errors due to the `build_stats` directory missing from the `commonTools` directory:

<details>

<summary><b>Configure error output</b> (click to expand)</summary>

```
-- The Current CXX Standard is : 17

Configuring Trilinos build directory

-- PROJECT_SOURCE_DIR='/Users/ndellin/Research/trilinos/TestPackageSource/trilinos-14.1-Source'
-- PROJECT_BINARY_DIR='/Users/ndellin/Research/trilinos/TestPackageSource/Build'
-- Trilinos_TRIBITS_DIR='/Users/ndellin/Research/trilinos/TestPackageSource/trilinos-14.1-Source/cmake/tribits'
-- TriBITS_VERSION_STRING='0.9 (Dev)'
-- CMAKE_VERSION='3.24.4'
-- CMAKE_GENERATOR='Unix Makefiles'
-- CMAKE_HOST_SYSTEM_NAME='Darwin'
-- Trilinos_HOSTNAME='s1067110'
-- PYTHON_EXECUTABLE='/opt/local/bin/python'

Setting up major user options ...

CMake Error at cmake/CallbackSetupExtraOptions.cmake:91 (include):
  include could not find requested file:

    /Users/ndellin/Research/trilinos/TestPackageSource/trilinos-14.1-Source/commonTools/build_stats/BuildStatsWrappers.cmake
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1167 (include)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1292 (tribits_repository_setup_extra_options_runner)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:140 (tribits_process_extra_repos_options_files)
  cmake/tribits/core/package_arch/TribitsProject.cmake:92 (tribits_project_impl)
  CMakeLists.txt:126 (TRIBITS_PROJECT)


CMake Error at cmake/CallbackSetupExtraOptions.cmake:92 (generate_build_stats_wrappers):
  Unknown CMake command "generate_build_stats_wrappers".
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1167 (include)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1292 (tribits_repository_setup_extra_options_runner)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:140 (tribits_process_extra_repos_options_files)
  cmake/tribits/core/package_arch/TribitsProject.cmake:92 (tribits_project_impl)
  CMakeLists.txt:126 (TRIBITS_PROJECT)


-- Configuring incomplete, errors occurred!
See also "/Users/ndellin/Research/trilinos/TestPackageSource/Build/CMakeFiles/CMakeOutput.log".
```

</details>

Copying the missing `commonTools/build_stats` from the original Trilinos source to the packaged source directory allows for configuration and compilation 

### Steps to Reproduce

1. SHA1:  fba42cea7c742468adcecb5b0201e5d12ef07703
2. Steps with just Teuchos enabled using gnu compilers

<details>

<summary><b>Reproduction details</b> (click to expand)</summary>

```bash
# Part 1: Simple configuration of Trilinos and run make package_source to generate packaged source code tarballs
mkdir -p build
cd build

cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_INSTALL_PREFIX=$PWD/install -DTrilinos_ENABLE_Teuchos=ON -DTeuchos_ENABLE_TESTS=OFF $TRILINOS_DIR

make package_source
# This will create e.g. trilinos-14.1-Source.tar.gz


# Part 2: Attempt to configure from the packaged source

# Create a new build directory to test the packaged source
mv trilinos-14.1-Source.tar.gz ..
cd ..
tar -zxv trilinos-14.1-Source.tar.gz
mkdir -p build_package_source
cd build_package_source

cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_INSTALL_PREFIX=$PWD/install -DTrilinos_ENABLE_Teuchos=ON -DTeuchos_ENABLE_TESTS=OFF $PWD/../trilinos-14.1-Source
# At this point configuration errors occur
```

</details>

## Tasks

* [x] Fix immediate problem in Trilinos (see PR #11977)
* [ ] Apply TriBITS fix to TriBITS repo and add missing TriBITS test case
* [ ] Experiment with trying to keep `commonTools/build_stats` even if the `TrilinosBuildStats` package is not enabled (e.g. by removing the exclude from `CPACK_SOURCE_IGNORE_FILES` in the file `cmake/CallbackDefineRepositoryPackaging.cmake`)
* [ ] Add new Trilinos tests to the `TrilinosInstallTests` package to test tarball creation and configure from expanded tarball source tree

**Comment by ndellingwood** [comment]
Adding @dmdunla , he initially reported this on project we work on

**Comment by bartlettroscoe** [comment]
@ndellingwood and @dmdunla, I don't think anyone has created a source tarball for Trilinos in many years and there is no automated testing for this, so I am not surprised this failed.  With that being the case, I can see what the problem is and put in a fix and set up an automated test as part of the Trilinos test suite for this if that is okay with @sebrowne and @ccober6.  Otherwise, if no automated testing is going to be set up and run to protect these feature, then Trilinos should announce that creating source tarballs is not supported.

@sebrowne and @ccober6, what say you?  Is Trilinos going to support creating source tarballs going forward?

**Comment by ndellingwood** [comment]
Thanks @bartlettroscoe ! 
The driver for using the package_source feature and tarballs is that it results in a much reduced size for Trilinos, which can be useful (sometimes necessary) for distributing the code to systems unable to access github/internet

**Comment by bartlettroscoe** [comment]
> Thanks @bartlettroscoe ! The driver for using the package_source feature and tarballs is that it results in a much reduced size for Trilinos, which can be useful (sometimes necessary) for distributing the code to systems unable to access github/internet

@ndellingwood, I am well aware of the advantages.  The TriBITS automatically support for trimming down the source tall-ball based on what package are enabled (or not enabled for the tarball excludes) was extensively used in CASL VERA project (for removing sensitive packages for some reduced releases as well as reducing source size.

The question is not if this feature is useful (it clearly is for some customers); the question is if Trilinos is willing to support it.  But supporting this is not that hard and I could write a basic set of tests to do this that could run as part of Trilinos PR and nightly testing.  (The test would create the source tarball for whatever set of Trilinos packages was enabled and would untar and try to configure the reduced Trilinos source as part of the test.)

**Comment by bartlettroscoe** [comment]
The issue is that the directory `commonTools/build_stats` is also a TriBITS package called `TrilinosBuildStats` (so it can run a set of automated tests).  When the package `TrilinosBuildStats` is not enabled, TriBITS automatically excludes the package directory for that package (see [Creating a tarball of the source tree](https://docs.trilinos.org/files/TrilinosBuildReference.html#creating-a-tarball-of-the-source-tree)).

The fix is to guard this code based on the existence of the directory  `commonTools/build_stats`.  I will put in a PR against 'develop' that fixes this.

**Comment by bartlettroscoe** [comment]
@ndellingwood and @dmdunla, this should be fixed in PR #11977.  The local testing I did seems to suggest this should work.  But if you would like to test this for your exact use case before this PR gets merged, that would be greatly appreciated :-)

**Comment by bartlettroscoe** [comment]
@ndellingwood, @sebrowne, @ccober6,

I added a **Tasks** section [above](https://github.com/trilinos/Trilinos/issues/11976#issue-1757789786) for the remaining work to put some reasonable checks in place for the ability to create and configure/build/test/install from reduced tarballs. 

But note that even though you can create a reduced tarball and configure from it, that does not guarantee that the enabled packages from the reduced source tree will build, pass the tests, and install successfully.  The issue is that some Trilinos packages might have have hooks into other non-enabled packages (like grabbing tests files from another package) that may be missing from the untarred reduced source tree.  The only way to know for sure would be to build, test, and install from the reduced tarball.  (We did that on the CASL VERA project but it requires some more testing infrastructure to do that.  It is actually not that hard to set up but that involves a lot more build and test time.)

**Comment by bartlettroscoe** [comment]
> We configure first so that all of the dependencies are resolved. Then, when we call `make package_source` we (seem) to get everything that we need across the packages that we configured for. If there is a different approach we should use, please clarify. Thanks! 

@dmdunla,

That is it which is consistent with:

* https://docs.trilinos.org/files/TrilinosBuildReference.html#creating-a-tarball-of-the-source-tree

Just make sure you follow that carefully (especially the part about running `git clean -fd -x` first to clean up everything in case you have other stuff in your source tree).

**Comment by bartlettroscoe** [comment]
@ndellingwood and @dmdunla,

With the merge of PR #11977 to 'develop', this should be working again.  If it is not, please let me know.
