### ISSUE TITLE
Tpetra: Removal of deprecated code meta issue

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5602]
## Bug Report
@trilinos/tpetra 

### Description
Meta issue to track work to remove deprecated code from @trilinos/tpetra

The work (so far) concentrates on two configurations, each with deprecated code **disabled**:

1. Tpetra's global ordinal = `int` (`TPETRA_INST_INT_INT:BOOL=ON`)
2. Tpetra's global ordinal = the default value (`long long int`)

Each configuration has build and/or test problems outlined in the following comments.

*Related PRs*
- #5590 
- #5573 

*Related Issues*
- #5537 
- #5538 
- #5540 
- #5541 
- #5592 
- #5593 
- #5594 
- #5595 

*Supersedes*
- #5536

**Comment by tjfulle** [comment]
# Status for `GlobalOrdinal=int`, `LocalOrdinal=int`

## Configuration and Build

With deprecated code disabled and using the default Tpetra `GlobalOrdinal`, the
build fails due to inconsistencies between Tpetra's global ordinal and Epetra.
For instance, Xpetra fails to build because it requires that Tpetra's global
ordinal be `int` when Epetra is enabled.  The solution is to disable Epetra
support in this and other packages, or set the global ordinal to `int`, as in
the configuration below.

Note, the configuration options file below requires that
`${TRILINOS_DIR}/cmake/std/sems/PullRequestGCC7.3.0TestingEnv.sh` be sourced.

```
#!/bin/sh
rm -rf CMake*
  cmake
  -G "Ninja" \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Tpetra_INST_INT_INT:BOOL=ON \
  -D Trilinos_CONFIGURE_OPTIONS_FILE:FILEPATH=${TRILINOS_DIR}/cmake/std/PullRequestLinuxCommonTestingSettings.cmake \
  -DTpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  -DXpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  -D Trilinos_ENABLE_STK:BOOL=OFF \
  -D ROL_ENABLE_EXAMPLES:BOOL=OFF \
  ${TRILINOS_DIR}
```

## Failing tests

- [x] Amesos2_GappedMtxGIDs-1proc_MPI_1
- [ ] Amesos2_KLU2_UnitTests_MPI_2
- [ ] Belos_resolve_gmres_hb_1_MPI_4
- [ ] Ifpack2_AdditiveSchwarz_MPI_4
- [ ] MueLu_BlockedTransfer_Tpetra_MPI_4
- [ ] MueLu_DriverEpetra_CircNspDependency_MPI_4
- [ ] MueLu_DriverEpetra_IsorropiaPoisson_MPI_4
- [ ] MueLu_ParameterListInterpreterTpetra_MPI_1
- [ ] MueLu_UnitTestsEpetra_MPI_1
- [ ] MueLu_UnitTestsIntrepid2Tpetra_MPI_1
- [ ] MueLu_UnitTestsIntrepid2Tpetra_MPI_4
- [ ] MueLu_UnitTestsTpetra_MPI_1
- [ ] MueLu_UnitTestsTpetra_MPI_4
- [ ] MueLu_VarDofDriver_MPI_1
- [ ] MueLu_VarDofDriver_MPI_2
- [ ] PanzerDiscFE_LinearObjFactory_Tests_MPI_2
- [ ] Rythmos_IntegratorBuilder_ConvergenceTest_MPI_1
- [ ] ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_DIM2_DPN2_ORD0_TPETRA_MPI_4
- [ ] ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_DIM2_DPN2_ORD1_TPETRA_MPI_4
- [ ] Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial_MPI_4
- [ ] Teko_testdriver_tpetra_MPI_1
- [ ] Teko_testdriver_tpetra_MPI_4
- [ ] Tempus_BDF2_Combined_FSA_MPI_1
- [ ] Tempus_BDF2_MPI_1
- [ ] Tempus_BackwardEuler_Combined_FSA_MPI_1
- [ ] Tempus_BackwardEuler_MPI_1
- [ ] Tempus_BackwardEuler_Staggered_FSA_MPI_1
- [ ] Tempus_DIRK_ASA_MPI_1
- [ ] Tempus_DIRK_Combined_FSA_SDIRK_5_Stage_4th_Order_MPI_1
- [ ] Tempus_DIRK_Combined_FSA_SDIRK_5_Stage_5th_Order_MPI_1
- [ ] Tempus_ExplicitRK_ASA_MPI_1
- [ ] Tempus_HHTAlpha_MPI_1
- [ ] Tempus_IMEX_RK_Combined_FSA_MPI_1
- [ ] Tempus_IMEX_RK_Partitioned_Combined_FSA_Partitioned_IMEX_RK_1st_Order_MPI_1
- [ ] Tempus_IMEX_RK_Partitioned_Staggered_FSA_Partitioned_IMEX_RK_1st_Order_MPI_1
- [ ] Tempus_IMEX_RK_Staggered_FSA_MPI_1
- [ ] Tempus_Newmark_MPI_1
- [ ] Xpetra_Cloner_UnitTests_MPI_4
- [ ] Zoltan2_GraphModel2ndAdjsFromAdjs_MPI_4
- [ ] Zoltan2_Metric_MPI_4
- [ ] Zoltan2_TaskMapper_MPI_4
- [ ] Zoltan2_TaskMappingProblemTest_MPI_4
- [ ] Zoltan2_componentMetrics_MPI_4
- [ ] Zoltan2_pamgenMeshAdapterTest_ghosthg_MPI_4
- [ ] Zoltan2_simplePamgenTest_MPI_3

**Comment by tjfulle** [comment]
# Status with `GlobalOrdinal=<default>` and `LocalOrdinal=<default>`

## Configuration and Build

Like the previous comment, with deprecated code disabled, all downstream packages enabled, and using the default Tpetra GlobalOrdinal, the build fails for a variety of reasons.  Many packages need to be disabled to get a build to completion.

Note, the configuration options file below requires that
${TRILINOS_DIR}/cmake/std/sems/PullRequestGCC7.3.0TestingEnv.sh be sourced.

## Final (Working) Configuration

```
/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.12.2/bin/cmake \
  -G "Ninja" \
  -D Trilinos_CONFIGURE_OPTIONS_FILE:FILEPATH=/home/tjfulle/Developer/repos/github.com/tjfulle/Trilinos/develop/cmake/std/PullRequestLinuxCommonTestingSettings.cmake \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=OFF \
  -D Trilinos_ENABLE_Moertel:BOOL=OFF \
  -D Trilinos_ENABLE_ShyLU_DDFROSch:BOOL=OFF \
  -D Trilinos_ENABLE_Stokhos:BOOL=OFF \
  -D ROL_ENABLE_EXAMPLES:BOOL=OFF \
  -D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  -D Xpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  -D Trilinos_ENABLE_Galeri:BOOL=OFF \
  -D Rythmos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_FEI:BOOL=OFF \
  -D MueLu_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_Panzer:BOOL=OFF \
  /home/tjfulle/Developer/repos/github.com/tjfulle/Trilinos/develop
```

## Failing Tests

- [ ] Zoltan2_GraphModel2ndAdjsFromAdjs_MPI_4 (Failed)
- [ ] Zoltan2_Metric_MPI_4 (Failed)
- [ ] Zoltan2_componentMetrics_MPI_4 (Failed)
- [ ] Zoltan2_TaskMapper_MPI_4 (Failed)
- [ ] Zoltan2_TaskMappingProblemTest_MPI_4 (Failed)
- [ ] Zoltan2_pamgenMeshAdapterTest_ghosthg_MPI_4 (Failed)
- [ ] Zoltan2_simplePamgenTest_MPI_3 (Failed)
- [x] Amesos2_GappedMtxGIDs-1proc_MPI_1 (Failed)

**Comment by brian-kelley** [comment]
@tjfulle I fixed the Ifpack2_AdditiveSchwarz_MPI_4 tests, and made a pull request into your branch "issue-5536". Is that the right way to merge it, or should I PR straight to origin/develop? 

https://github.com/tjfulle/Trilinos/pull/2

**Comment by mhoemmen** [comment]
PR https://github.com/trilinos/Trilinos/pull/5573 merged, so Stokhos builds now with Tpetra deprecated code OFF and GO=int OFF.

**Comment by GeoffDanielson** [comment]
@tjfulle , I am unable to make Belos_resolve_gmres_hb_1_MPI_4 fail with G0 = LO = int

**Comment by GeoffDanielson** [comment]
@tjfulle I am also unable to make Rythmos_IntegratorBuilder_ConvergenceTest_MPI_1 with GO = LO = int.

**Comment by kddevin** [comment]
@tjfulle I am running tempus now, but not seeing failures in some of the tests that were reported as failures.  Perhaps the rebase from develop pulled in solutions.  

I will report all tempus results once them run to completion; the tempus tests take a long time on my workstation.

Zoltan2 fixes are in PR #5645 and will soon be merged with develop (I hope).

**Comment by kddevin** [comment]
Some teko fixes are in #5651

**Comment by tjfulle** [comment]
@kddevin My latest push now fixes many of the issues above.  The branch now has so many modifications in so many packages that I think it will be beneficial to cherry pick out changes by package and open PRs for each package individually - that's what I am working on now.

**Comment by tjfulle** [comment]
Half a dozen or so PRs have been opened.  Once they start to get through testing and get merged in to develop, I'll revisit the build/test with deprecated code off.  Hopefully it's getting much closer!

**Comment by brian-kelley** [comment]
There are now 3 nightly builds with deprecated off:

- [GO=int](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=4886217). Currently, one Xpetra test failure and a bunch of STK build errors because it wants GO=long long.
- [GO=long long](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=4886086). Because Epetra32 is on, Xpetra has a config error saying that Tpetra must also have GO=int enabled. There are also several build errors in ROL, TrilinosCouplings and Piro.
- [Basic build with Tpetra/Epetra but no downstream](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=4885635): clean.

@tjfulle If you're not already working on these, I can look at the ROL build errors in GO long long today and tomorrow.
