### ISSUE TITLE
Set up unit testing infrastructure for ATDM Trilinos bash-based scripts

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#5939]
## Description:

The ATDM Trilinos system composed of bash scripts is complex enough that we need to start adding automated testing for the bash functions and scripts.

## Tasks:

- [X] Find a bash unit test harness and experiment with one ... Selected https://github.com/kward/shunit2/ ... PR #7202 
- [X] Create a Triinos TriBITS package called TrilinosATDMConfigTests ... PR #7202 
- [X] Write unit tests for atdm/utils/set_build_options.sh ... PR #7202
- [x] Write unit tests for atdm/utils/get_system_info.sh (both supported and custom systems).
- [ ] Write unit tests for atdm/load-env.sh (both known supported and custom systems).
- [ ] Run a basic local configure, build, and install for some faster building and running Trilinos packages (e.g. TeuchosCore) using atdm/ctest-s-local-test-driver.sh for 'sems-rhel7' env (only if that env is available) and ensure that the installation happens and has the right parts and they work correctly (i.e. `<prefix>/load_matching_env.sh`). (This can run in PR testing for one more more of the Trilinos PR builds since these run in RHEH7 machines that have the SEMS env.)

**Comment by bartlettroscoe** [comment]
This looks pretty close to what we need:

* https://github.com/kward/shunit2/

**Comment by bartlettroscoe** [comment]
CC: @e10harvey 

It just occurred to me how we might be able to do poor-man's unit testing with bash code without needing an elaborate unit test harness (and therefore another dependency).  I think I am going to experiment with that quickly.

**Comment by bartlettroscoe** [comment]
I am looking at:

* https://github.com/kward/shunit2

some and a few things I see that I don't like:

* There a quite a few files.  It is not all that small (but they are trying to support a bunch of different shells)
* It supports reporting line numbers but not fine names in the error messages
* Does not print out the names of vars being checked.
* Does not print out the functions being called and checked.
* It does not have any tests of its own (how can I know the unit test harness actually works?)

I am going to download this tool and play with this a little and see what I can learn but I think I want to build my own small little unit test harness in bash that will have:

* Add asserts that will print the vars being checked and the functions being called.
* All asserts will support file name and line number reporting.
* It will report the total number of tests run and the number of total asserts and passing asserts (so I can grep for that in CTest).
* Some unit testing of itself (raw bash tests).

**Comment by bartlettroscoe** [comment]
Okay, I have been using shunit2 for a little bit here and it is good enough for what I need and it has some nice features.  I am going to just snapshot a version of this under Trilinos/cmake/std/atdm/test/sunit2 and be done with it.  It is not that large and it has a very flexible Apache 2 license that should not give any customer a problem.

**Comment by bartlettroscoe** [comment]
CC: @e10harvey 

I have made a very good start on this in PR #7202.  That adds very strong unit testing to the script `atdm/utils/set_build_options.sh`.

The next may bit of unit testing will be to test the `atdm/utils/get_system_info.sh` script (and therefore the `atdm/utils/get_known_system_info.sh` script.  

Then we could unit test the `atdm/loa-env.sh` script as well if we create some dummy test envs that don't load any modules but only set env vars.

**Comment by bartlettroscoe** [comment]
With the recent merge of PR #8013 and the soon-to-be-merged PR #8026, I think we have some pretty decent unit testing in place.

The last thing to unit test in the `atdm/load-env.sh` script.  I think that will be easy to do with the addition of the test custom env:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/test/unit_tests/dummy_custom_system/

That will ensure that the basic mechanics work as they should.
