### ISSUE TITLE
Belos/Tpetra: Add Pipelined CG

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#748]
@trilinos/belos @trilinos/tpetra 

Epic: #767.

Add a Pipelined CG implementation (see e.g., work by Pieter Ghysels and Paul Eller).  I'm calling this a "story" because it has a few steps:
1. [x] #752: Implement a generic interface to MPI_Iallreduce
2. [x] #753, #1013: Implement Tpetra functions for nonblocking dot products
3. [ ] Implement a "native" Tpetra implementation of Pipelined CG (see #734 for a standard CG example)
4. [x] #754, #953: Make it possible to extend Belos::SolverFactory with custom Tpetra solvers
5. [ ] Wrap the native solver in a Belos::SolverManager subclass (extending #734; include stubs for making the subclass throw if given a non-Tpetra linear algebra implementation)
6. [ ] Actually make Pipelined CG available, using the previous steps.

Step 5 (wrapping the native Tpetra-based solver) requires a partial specialization of Belos::SolverFactory for Tpetra objects, since BelosTpetra lives downstream of Belos proper.  To avoid redundant code, it would be nicer to add a internal factory for Belos' generic implementations, and then have a hook for adding a factory of implementations native to the linear algebra.

**Comment by srajama1** [comment]
@hkthorn @srajama1

**Comment by mhoemmen** [comment]
Fixed a while back, in master.
