### ISSUE TITLE
ATDM Config: Change how compiler flags are handled

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#8449]
CC: @rppawlo, @trilinos/framework 

## The Problem

The current ATDM Trilinos configuration setup does not let the user pass in compiler flags using cache vars `CMAKE_CXX_FLAGS` without overriding the few special flags that the ATDM Trilinos configuration is setting like `--remove-duplicate-link-files` for CUDA+RDC builds and `-fPIC` for `fpic` builds (see https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#build-name-keywords).  The current implementation for setting these variables is shown in:

https://github.com/trilinos/Trilinos/blob/e29f0be643de0d55a202263ef1da8d4bc9c8001c/cmake/std/atdm/ATDMDevEnvSettings.cmake#L227..L236

which currently shows:

```
ATDM_SET_CACHE(CMAKE_C_FLAGS
  "$ENV{ATDM_CONFIG_C_FLAGS} $ENV{EXTRA_C_FLAGS}" CACHE STRING)
ATDM_SET_CACHE(CMAKE_CXX_FLAGS
  "$ENV{ATDM_CONFIG_CXX_FLAGS}${EXTRA_EXTRA_CXX_FLAGS} $ENV{EXTRA_CXX_FLAGS}" CACHE STRING)
ATDM_SET_CACHE(CMAKE_Fortran_FLAGS
  "$ENV{ATDM_CONFIG_Fortran_FLAGS} $ENV{EXTRA_Fortran_FLAGS}" CACHE STRING)
# NOTE: That above "EXTRA_<LANG>_FLAGS" env vars are left in for backward
# compatibility with the EMPIRE configuration and are not directly set in any
# offical ATDM Trilinos configuration setup.  Only the
# "ATDM_CONFIG_<LANG>_FLAGS" env vars are set.
```

This leads to confusing behavior like resulted in https://github.com/TriBITSPub/TriBITS/issues/341 and [ATDV-415](https://sems-atlassian-srn.sandia.gov/browse/ATDV-415).

From reading the section "14.3. Compiler And Linker Variables" in the book "Professional CMake: A Practical Guide (5th edition)", it seems that the most acceptable way to set these vars is to set local non-cache vars and either prepend or append to the cache vars.

## Suggested Change

Given that I doubt that any EMPIRE developers are still using the env vars `EXTRA_<LANG>_FLAGS`, we should just go with the approach of prepending to the user-set cache vars using project-scope non-cache vars like:

```
SET(CMAKE_CXX_FLAGS
  "$ENV{ATDM_CONFIG_CXX_FLAGS}${EXTRA_EXTRA_CXX_FLAGS} ${CMAKE_CXX_FLAGS}")
```

That way, when the user configures with:

```
-DCMAKE_CXX_FLAGS="<flag1> <flag2> ..."
```

then those flags would come after (can therefore override) any flags being set internally but will not wipe out important flags like `--remove-duplicate-link-files` and `-fPIC`.

## Tasks:

* [ ] Create branch '8449-atdm-compliler-flags-fix'
* [ ] Implement change described above
* [ ] Add section to `atdm/README.md` on how compiler flags work and how to extend and override them
* [ ] Do local testing to ensure that set flags are working (and test adding new flags with `-DCMAKE_CXX_FLAGS=<extra_flags>`)
* [ ] Post PR for branch '8449-atdm-compliler-flags-fix' and get it merged

**Comment by bartlettroscoe** [comment]
@rppawlo, are you okay with the change suggested above?  It will be as easy to make that change and document it as it would be to document the existing implementation copied over from the old EMPIRE Trilinos configure scripts.

**Comment by rppawlo** [comment]
yes. Thanks!

**Comment by bartlettroscoe** [comment]
@rppawlo, I forgot about this but was just reminded of this looking at [CII Best Practices build_standard_variables](https://bestpractices.coreinfrastructure.org/en/criteria#1.build_standard_variables).

I can make this change pretty easily but there is the issue of making sure this does not break any of the existing ATDM Trilinos builds.  The risk is low but that is no longer my decision anymore.

**Comment by rppawlo** [comment]
yeah - it would be good to get this change in if you have time.

**Comment by bartlettroscoe** [comment]
@rppawlo, PR #9092 implements the fix described [above](https://github.com/trilinos/Trilinos/issues/8449#issue-761328250).

**Comment by bartlettroscoe** [comment]
With the merge of PR #9092 this is complete.
