### ISSUE TITLE
Tpetra:  finalize interface changes and enable deprecated warnings

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#9799]
## Enhancement
@trilinos/tpetra 

Several Tpetra interfaces changed due to removal of the UVM requirement from Tpetra.  To be user-friendly during Tpetra-stack conversion to the new interfaces, we suppressed the deprecation warnings.  @trilinos/tpetra will review the remaining interfaces and decide which need to be deprecated as well.  We will enable deprecation warnings as we go along.

- [x] Deprecations due to UVM removal
- [x] CrsMatrix constructors that take profileType as argument  #9865
- [x] Rsend and Ssend options in Distributor #9852 #9873
- [x] Return packed views always in getNodePackedIndices, getNodeRowPtrs, getAllValues #9885 
- [x] ArrayView interfaces to Distributor #10164  
- [x] methods getNode* are now getLocal* #10189 
- [ ] Graph and Matrix accessors now use access tags #10188

**Comment by tasmith4** [comment]
@csiefer2 guessing this can be closed now since #10552 is merged?

**Comment by csiefer2** [comment]
Sure.
